"""add_refresh_tokens_table

Revision ID: 1906e8b727d2
Revises: fbea1868d5e6
Create Date: 2026-04-18 09:52:21.543872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1906e8b727d2'
down_revision: Union[str, None] = 'fbea1868d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_refresh_tokens_family', ['family_id'], unique=False)
        batch_op.create_index('idx_refresh_tokens_hash', ['token_hash'], unique=True)
        batch_op.create_index('idx_refresh_tokens_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('idx_refresh_tokens_user')
        batch_op.drop_index('idx_refresh_tokens_hash')
        batch_op.drop_index('idx_refresh_tokens_family')

    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
