"""add_waitlist_signups

Revision ID: 383e457f2a26
Revises: b99d9a6cbc0e
Create Date: 2026-05-23 09:02:08.777298

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '383e457f2a26'
down_revision: Union[str, None] = 'b99d9a6cbc0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist_signups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('signup_intent', sa.String(length=50), nullable=True),
    sa.Column('consent_text', sa.String(length=1000), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # Índice funcional para idempotencia case-insensitive
    op.execute(
        "CREATE UNIQUE INDEX waitlist_signups_email_lower_idx "
        "ON waitlist_signups (LOWER(email))"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS waitlist_signups_email_lower_idx")
    op.drop_table('waitlist_signups')
