"""add_token_budget_columns

Revision ID: 40b89212052d
Revises: scrub_phi_from_scan_history
Create Date: 2026-05-19 09:45:46.163326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b89212052d'
down_revision: Union[str, None] = 'scrub_phi_from_scan_history'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_analytics_event'))
        batch_op.drop_index(batch_op.f('idx_analytics_user'))
        batch_op.create_index('idx_analytics_events_user', ['user_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_products_category'))
        batch_op.drop_index(batch_op.f('idx_products_clean_score'))
        batch_op.drop_index(batch_op.f('idx_products_needs_barcode_link'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens_used_today', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('tokens_budget_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('tokens_budget_date')
        batch_op.drop_column('tokens_used_today')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_products_needs_barcode_link'), ['needs_barcode_link'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_clean_score'), ['clean_score'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_category'), ['category'], unique=False)

    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index('idx_analytics_events_user')
        batch_op.create_index(batch_op.f('idx_analytics_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_analytics_event'), ['event_type'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###
