"""add_off_contributions

Revision ID: 91b0a38b0422
Revises: 1906e8b727d2
Create Date: 2026-04-22 15:42:58.618853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b0a38b0422'
down_revision: Union[str, None] = '1906e8b727d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('off_contributions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scan_history_id', sa.String(length=36), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('ingredients_text', sa.Text(), nullable=False),
    sa.Column('image_submitted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('off_response_url', sa.String(length=500), nullable=True),
    sa.Column('off_error', sa.Text(), nullable=True),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scan_history_id'], ['scan_history.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('off_contributions', schema=None) as batch_op:
        batch_op.create_index('idx_off_contrib_status', ['status'], unique=False)
        batch_op.create_index('idx_off_contrib_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('off_contributions', schema=None) as batch_op:
        batch_op.drop_index('idx_off_contrib_user')
        batch_op.drop_index('idx_off_contrib_status')

    op.drop_table('off_contributions')
    # ### end Alembic commands ###
