"""add_share_token

Revision ID: b7493142c951
Revises: ef6c147ec0d4
Create Date: 2026-05-22 08:43:23.483757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7493142c951'
down_revision: Union[str, None] = 'ef6c147ec0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('share_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_scan_history_share_token'), ['share_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_history_share_token'))
        batch_op.drop_column('share_expires_at')
        batch_op.drop_column('share_token')

    # ### end Alembic commands ###
