"""initial_schema

Revision ID: fbea1868d5e6
Revises: 
Create Date: 2026-04-16 13:27:54.506534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbea1868d5e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('source_checksum', sa.String(length=71), nullable=True),
    sa.Column('license', sa.String(length=50), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('cas_number', sa.String(length=20), nullable=True),
    sa.Column('e_number', sa.String(length=10), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cas_number')
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_index('idx_ingredients_cas', ['cas_number'], unique=False)
        batch_op.create_index('idx_ingredients_e_number', ['e_number'], unique=False)
        batch_op.create_index('idx_ingredients_entity_id', ['entity_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('idx_products_barcode', ['barcode'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('biomarkers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_data', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_iv', sa.LargeBinary(length=16), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biomarkers', schema=None) as batch_op:
        batch_op.create_index('idx_biomarkers_user', ['user_id'], unique=False)

    op.create_table('conflicts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('conflict_type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.create_index('idx_conflicts_ingredient', ['ingredient_id'], unique=False)
        batch_op.create_index('idx_conflicts_unresolved', ['resolved'], unique=False)

    op.create_table('ingestion_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('ingestion_id', sa.String(length=100), nullable=False),
    sa.Column('source_checksum', sa.String(length=71), nullable=False),
    sa.Column('data_version', sa.String(length=50), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingestion_id')
    )
    with op.batch_alter_table('ingestion_log', schema=None) as batch_op:
        batch_op.create_index('idx_ingestion_source', ['source_id'], unique=False)

    op.create_table('regulatory_status',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('usage_limits', sa.String(length=255), nullable=True),
    sa.Column('hazard_note', sa.Text(), nullable=True),
    sa.Column('data_version', sa.String(length=50), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'source_id', name='uq_reg_status_ingredient_source')
    )
    with op.batch_alter_table('regulatory_status', schema=None) as batch_op:
        batch_op.create_index('idx_reg_status_ingredient', ['ingredient_id'], unique=False)
        batch_op.create_index('idx_reg_status_source', ['source_id'], unique=False)

    op.create_table('scan_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product_barcode', sa.String(length=50), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=True),
    sa.Column('semaphore_result', sa.String(length=10), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('conflict_severity', sa.String(length=10), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='ck_scan_confidence'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['product_barcode'], ['products.barcode'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.create_index('idx_scan_history_barcode', ['product_barcode'], unique=False)
        batch_op.create_index('idx_scan_history_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.drop_index('idx_scan_history_user')
        batch_op.drop_index('idx_scan_history_barcode')

    op.drop_table('scan_history')
    with op.batch_alter_table('regulatory_status', schema=None) as batch_op:
        batch_op.drop_index('idx_reg_status_source')
        batch_op.drop_index('idx_reg_status_ingredient')

    op.drop_table('regulatory_status')
    with op.batch_alter_table('ingestion_log', schema=None) as batch_op:
        batch_op.drop_index('idx_ingestion_source')

    op.drop_table('ingestion_log')
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.drop_index('idx_conflicts_unresolved')
        batch_op.drop_index('idx_conflicts_ingredient')

    op.drop_table('conflicts')
    with op.batch_alter_table('biomarkers', schema=None) as batch_op:
        batch_op.drop_index('idx_biomarkers_user')

    op.drop_table('biomarkers')
    op.drop_table('users')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('idx_products_barcode')

    op.drop_table('products')
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index('idx_ingredients_entity_id')
        batch_op.drop_index('idx_ingredients_e_number')
        batch_op.drop_index('idx_ingredients_cas')

    op.drop_table('ingredients')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
